[Language] Java vs Python
brave-people/brave-tech-interview pull request #21
Opened 2021-04-06 23:24 UTC by osj3474

제가 면접 때 받았던 질문입니다.

면접관 : 어떤 언어가 제일 자신있어요?
저 : 파이썬입니다.
면접관 : 자바랑 파이썬이랑 어떻게 다르죠?
저 : 파이썬은 인터프리터 언어고,,, 자바는 컴파일 언어 아,,

이렇게밖에 대답하지 못했던 기억이 나네요. 같이 pr해서 이 내용도 추가해보면 좋을거 같습니다!

2021-04-07 12:09 UTC, KoEonYack requested changes
작업 전에  `git pull origin main` 으로 싱크를 맞추지 않아서   `sangjin` branch로 main pull했더니 language.md에 os.md랑 혼재되어있네요!

예를 들자면 sangjin에서 main pull 당긴 현재 커밋(제가 마지막으로 한 커밋) P NP 문제에대해서 설명하세요 문제가 없네요... git 상에서는 충돌이 안나는데 어디서 잘못된 부분이 있나봅니다.  language.md에 os.md 문제가 수록되어있고요.

제가 해결해보려고했는데 해야할 다른 일이 있어서 여기까지만 작업해두고 혹시 시간 괜찮으실때 문제상황을 살펴보세요~

앞으로 작업할때는 main과 싱크를 맞추어두고 작업하면 될꺼에요~~~

2021-04-07 12:09 UTC, KoEonYack commented on contents/language.md
> +| 실행   | [작동 방식]<br /><br />1) `컴파일러` : 모든 소스코드(.java) => 바이트코드(.class) <br />2) `JVM` : 운영체제에 맞는 기계어로 변환 <br /><br />=> 컴파일 시간이 소요되지만, 실행 속도는 빠름. | [작동 방식]<br /><br />1) `Interpreter` : 한 줄씩 해석하여 실행
Java Python 둘 다 "작동 방식"에 대해서 설명하는데 좌측 항목은 실행이라고 되어있네요!!

2021-04-07 13:18 UTC, osj3474 commented on contents/language.md
> +| 실행   | [작동 방식]<br /><br />1) `컴파일러` : 모든 소스코드(.java) => 바이트코드(.class) <br />2) `JVM` : 운영체제에 맞는 기계어로 변환 <br /><br />=> 컴파일 시간이 소요되지만, 실행 속도는 빠름. | [작동 방식]<br /><br />1) `Interpreter` : 한 줄씩 해석하여 실행
넵 해당 부분 수정하겠습니다~!!

2021-04-07 13:20 UTC, osj3474 commented
오 그러면, language.md는 없어지는 건가요?

(현재, language.md와 os.md의 내용이 같은거 같은데, 하나를 없애는 것인지 궁금합니다!)

2021-04-07 13:22 UTC, KoEonYack commented
아뇨~
main branch 기준으로 생각하면 됩니다.
language.md에 os.md 내용이 overwrite된것으로 보여요~ 물론 빠진 내용 있는지 봐야겠지만요~

2021-04-07 13:26 UTC, osj3474 commented
아하!! 그럼 main브랜치 기준으로 비교해보고 다시 pr올리겠습니당~~!

2021-04-07 14:04 UTC, KoEonYack commented
👍

2021-04-08 19:03 UTC, jihyunhillpark commented
오홍!! 
정적 타이핑과 동적타이핑 차이도 있숩니다!!!

2021-04-10 18:20 UTC, merged